const Sections = [
   {id:"1",
   name:"parents",
   ar:"الاباء",
   sections:
   [
    {id:"1",
    secname:"study",
    ar:"مذاكرة",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"alphabet",arname:"حروف",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"numbers",arname:"ارقام",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"drawing",arname:"رسم",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    {id:"2",
    secname:"problems",
    ar:"مشاكلهم",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"lie",arname:"كذب",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"disobey",arname:"العند",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"noty",arname:"فرط الحركة",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    {id:"3",
    secname:"skills",
    ar:"مهارات",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"social",arname:"اجتماعية",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"movement",arname:"حركية",img:"/assets/imgs/background/cloud11.png"},
    ]
    },
    
   ]
  },
  {id:"2",
   name:"stories",
   ar:"قصص ",
   sections:
   [
    {id:"1",
    secname:"comedy",
    ar:"كوميدي",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"com1",arname:"كوم1",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"com1",arname:"كوم2",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"com3",arname:"كوم3",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    {id:"2",
    secname:"action",
    ar:"اكشن",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"act1",arname:"اكشن1",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"act2",arname:"اكشن2",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"act3",arname:"اكشن3",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    {id:"3",
    secname:"art",
    ar:"فن",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"art1",arname:"فن1",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"art2",arname:"فن2",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"art3",arname:"فن3",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    {id:"4",
    secname:"artt",
    ar:"فن",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"art1",arname:"فن1",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"art2",arname:"فن2",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"art3",arname:"فن3",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    {id:"5",
    secname:"arth",
    ar:"فااان",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"art1",arname:"فن1",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"art2",arname:"فن2",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"art3",arname:"فن3",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    
   ]
  },
  {id:"3",
   name:"ideas",
   ar:"افكار",
   sections:
   [
    {id:"1",
    secname:"idea1",
    ar:"فكرة1",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"idea1",arname:"كوم1",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"idea2",arname:"كوم2",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"idea3",arname:"كوم3",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    {id:"2",
    secname:"idea2",
    ar:"فكرة2 ",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"idea1",arname:"كوم1",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"idea2",arname:"كوم2",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"idea3",arname:"كوم3",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    {id:"3",
    secname:"idea3",
    ar:"فكرة3",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"idea1",arname:"كوم1",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"idea1",arname:"كوم2",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"idea3",arname:"كوم3",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    
   ]
  },
  {id:"4",
   name:"games",
   ar:" العاب",
   sections:
   [
    {id:"1",
    secname:"pazzel",
    ar:"ترتيب الصور",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"level1",arname:"سهل",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"level2",arname:"متوسط",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"level3",arname:"صعب",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    {id:"2",
    secname:"diff",
    ar:"الاختلاف بين الصورتين",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"level1",arname:"سهل",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"level2",arname:"متوسط",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"level3",arname:"صعب",img:"/assets/imgs/background/cloud11.png"}
    ]
    },
    {id:"3",
    secname:"words",
    ar:"كلمات متقاطعة",
    img:"/assets/imgs/background/cloud11.png",
    sub:
    [
        {id:"1",subname:"level1",arname:"سهل",img:"/assets/imgs/background/cloud11.png"},
        {id:"2",subname:"level2",arname:"متوسط",img:"/assets/imgs/background/cloud11.png"},
        {id:"3",subname:"level3",arname:"صعب",img:"/assets/imgs/background/cloud11.png"}
    ]
    }
    
   ]
  }

];


export  {Sections};